Add assertions to help track down bug
    $ python matchip.py 10.1.3.0/24 10.1.3.240/32 24 32
    ipaddr1 =
    Traceback (most recent call last):
      File "matchip.py", line 67, in ?
	print "ipaddr1 =", subnettoip(ipaddr1)
      File "matchip.py", line 28, in subnettoip
	assert isinstance(subnet[0], int), type(subnet[0])
    AssertionError: <type 'long'>

This bug appears to be only in Python 2.4.  This is regarding the
int vs. long type of return argument from struct.unpack with "I"
(unsigned int).  At first I thought it was an int, but it seems it
is defined as a long, according to the 2.4 library reference.

http://docs.python.org/release/2.4/lib/module-struct.html